spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fileStorage
    password: root11
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

